### ISSUE TITLE
Ice adapter not redirecting output

### ISSUE THREAD

**Issue by Eternal-ll** [Eternal-ll/Ethereal-FAF-Client#15]
![image](https://user-images.githubusercontent.com/86099479/167314030-8b1e3fa0-3b34-4d2b-b118-29e2af21307c.png)

`System.InvalidOperationException: StandardError has not been redirected.
   at System.Diagnostics.Process.BeginErrorReadLine()
   at beta.Models.Ice.IceAdapterProcess..ctor(String playerId, String playerLogin, Int32 RpcPort, Int32 GpgNetPort) in C:\Users\Eternal\source\repos\Ethereal-FAF-Client\beta\Models\Ice\IceAdapterProcess.cs:line 46
   at beta.Models.Ice.IceAdapterClient..ctor(String playerId, String playerLogin) in C:\Users\Eternal\source\repos\Ethereal-FAF-Client\beta\Models\Ice\IceAdapterClient.cs:line 123
   at beta.Infrastructure.Services.GameSessionService.RunGame(GameLaunchData e) in C:\Users\Eternal\source\repos\Ethereal-FAF-Client\beta\Infrastructure\Services\GameSessionService.cs:line 233
`

**Comment by Eternal-ll** [comment]
it is not necessary to redirect, I use it only for Debug. Added compiler condition
