### ISSUE TITLE
Client wont launch as single file

### ISSUE THREAD

**Issue by Eternal-ll** [Eternal-ll/Ethereal-FAF-Client#19]
`Faulting application name: Ethereal.FAF.UI.Client.exe, version: 1.0.0.0, time stamp: 0x62ffea72
Faulting module name: KERNELBASE.dll, version: 10.0.22621.317, time stamp: 0x2da5b269
Exception code: 0xe0434352
Fault offset: 0x000000000008fa7c
Faulting process id: 0x0x4830
Faulting application start time: 0x0x1D8DC1ADEDD2BF5
Faulting application path: C:\Users\Eternal\source\repos\Ethereal-FAF-Client\Ethereal.FAF.UI.Client\bin\Release\net6.0-windows10.0.17763.0\publish\win-x64\Ethereal.FAF.UI.Client.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 91ee44cc-597b-4467-8991-c7565a368593
Faulting package full name: 
Faulting package-relative application ID: `

`Application: Ethereal.FAF.UI.Client.exe
CoreCLR Version: 6.0.922.41905
.NET Version: 6.0.9
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ethereal.FAF.UI.Client.App.Application_DispatcherUnhandledException(Object sender, DispatcherUnhandledExceptionEventArgs e) in C:\Users\Eternal\source\repos\Ethereal-FAF-Client\Ethereal.FAF.UI.Client\App.xaml.cs:line 178
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at System.Windows.Threading.Dispatcher.CatchExceptionStatic(Object source, Exception e)
   at System.Windows.Threading.ExceptionWrapper.CatchException(Object source, Exception e, Delegate catchHandler)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at Ethereal.FAF.UI.Client.App.Main()
`

**Comment by Eternal-ll** [comment]
I am thinking about light updater that will pull light dll to update user client, so i dont need single file anymore
